# logo
import turtle
import random
from turtle import *
color = ["pink", "yellow", "red", "blue", "green"]
a = turtle.Turtle()
a.shape("turtle")
a.pencolor(random.choice(color))
a.backward(1000)
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))
a.pencolor(random.choice(color))
a.forward(100)
a.backward(100)
a.forward(100)
a.backward(100)
a.forward(100)
a.pencolor(random.choice(color))
a.pensize(random.randint(0, 10))



