# welcome to super Space quiz!!!
print('Welcome to super Space quiz!!!!')
import pyttsx3
engine = pyttsx3.init()
print('question 1')
engine.say("question 1!!")
engine.runAndWait()
print("which of the following is not positively charged?")
engine.say("which of the following is not positively charged?")
engine.runAndWait()
print("option A. Black Hole")
engine.say("option A. Black Hole")
engine.runAndWait()
print("option B. Earth's core")
engine.say("option B. Earth's core")
engine.runAndWait()
print("option C. White hole")
engine.say("option C. White hole")
engine.runAndWait()
ans = input("enter your answer: ")
if ans == ("White hole"):
    print("well done!")
    engine.say("Well, done")
    engine.runAndWait()
else:
    print("Nice try but the answer is White hole!")
    engine.say("Nice try but the answer is White hole!")
    engine.runAndWait()
print("question 2")
engine.say("question 2!!")
engine.runAndWait()
print("Any object whose mass is 0 has the speed of")
engine.say("Any object whose mass is 0 has the speed of")
engine.runAndWait()
print("option A. about 343 m/s")
